# Generated by Django 6.1.1 on 2026-09-14 11:02

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('start_date'), models.F('end_date'), models.F('organiser'), name='unique_event_name_dates_per_organiser')],
            },
        ),
    ]
