# Generated by Django 6.1.1 on 2026-09-17 11:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('access_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='access.accesslink')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email')), models.F('event'), name='unique_participant_email_per_event')],
            },
        ),
        migrations.CreateModel(
            name='PendingListUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('staff', 'Staff')], max_length=20)),
                ('rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('organiser'), models.F('event'), models.F('role'), name='unique_pending_list_upload_per_organiser_event_role')],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('access_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to='access.accesslink')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='events.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email')), models.F('event'), name='unique_staff_member_email_per_event')],
            },
        ),
    ]
